apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny
  namespace: helpdeskflow
  labels:
    app.kubernetes.io/part-of: helpdeskflow
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
