apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: helpdeskflow-db-pvc
  namespace: helpdeskflow
  labels:
    app.kubernetes.io/name: helpdeskflow-db
    app.kubernetes.io/part-of: helpdeskflow
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
