apiVersion: v1
kind: Service
metadata:
  name: helpdeskflow-db
  namespace: helpdeskflow
  labels:
    app.kubernetes.io/name: helpdeskflow-db
    app.kubernetes.io/part-of: helpdeskflow
spec:
  selector:
    app.kubernetes.io/name: helpdeskflow-db
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
  type: ClusterIP
