apiVersion: v1
kind: Secret
metadata:
  name: helpdeskflow-secrets
  namespace: helpdeskflow
  labels:
    app.kubernetes.io/name: helpdeskflow
    app.kubernetes.io/part-of: helpdeskflow
type: Opaque
stringData:
  DB_PASSWORD: helpdeskflow
  JWT_SECRET: change-me-in-minikube
  INTERNAL_SERVICE_TOKEN: change-me-internal-token
  SMTP_USER: ""
  SMTP_PASS: ""
  SEED_SUPPORT_PASSWORD: Support123!
  SEED_ADMIN_PASSWORD: Admin123!
