apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: helpdeskflow
  labels:
    app.kubernetes.io/name: api-gateway
    app.kubernetes.io/part-of: helpdeskflow
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: api-gateway
  template:
    metadata:
      labels:
        app.kubernetes.io/name: api-gateway
        app.kubernetes.io/part-of: helpdeskflow
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: api-gateway
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: api-gateway
                topologyKey: kubernetes.io/hostname
      containers:
        - name: api-gateway
          image: rafals12390/helpdeskflow-api-gateway:v0.2.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: API_GATEWAY_PORT
              valueFrom:
                configMapKeyRef:
                  name: helpdeskflow-config
                  key: API_GATEWAY_PORT
            - name: AUTH_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: helpdeskflow-config
                  key: AUTH_SERVICE_URL
            - name: USER_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: helpdeskflow-config
                  key: USER_SERVICE_URL
            - name: TICKET_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: helpdeskflow-config
                  key: TICKET_SERVICE_URL
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 20
            periodSeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 400m
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: helpdeskflow
  labels:
    app.kubernetes.io/name: api-gateway
    app.kubernetes.io/part-of: helpdeskflow
spec:
  selector:
    app.kubernetes.io/name: api-gateway
  ports:
    - name: http
      port: 8080
      targetPort: http
  type: ClusterIP
